apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: network-traffic-monitor-hpa-8085
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: network-traffic-monitor-deployment-8085
  minReplicas: 2
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 3  # Lower the CPU target to 3%
